language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"
script: mvn verify
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy
  --settings settings/maven/settings.xml
env:
  global:
  - secure: dKRAKAKYMSsB9HKUwQ4rIvW9F7TK1qVt7kfk5+ltAPwWK8pmWF6fxzyYNg/lxEfW8h8buMbkuElzgdlEESHl4gK+BfSy3acUkzzJrOOYw5u3m+z5uOzLLkEM9yPM6dqwPLMBLCOZIvboEZLFmiEXsE1nXW8m48rnERczyolBe3Cn3eP9+pVYCme0T0VHsq1u8PLOc/4K+X5F19dgU6UniWfViCToBgmzT3dDsESVYJEJNXqlacOKM73l5T4h+kbZsedVkfNCPQ0ZTb75ZzmGST0G2WpvRWmuf54jFRflDX+QGXN0L1KknLyMsZ0ZJ5XG7Mm9AgkJyECAP/ioLaUC47dy4qPQp5FQKCLUmcekxan//CWFmO//ty++cAMcpKUsUOv2wSs3veJtNY2WLBOe2hwiyIz9WsOEKDpg9l3AWefBrb2oKiod/q7H3EPlw56vVvgmvlTxngs7QztwY1PZoRZZ6nIshN95bLIXuq/Jt5p8TVa8w0Zshoz08FKaDqyqdQqcDJHEZFmtvPHKrHNBBOQ+Kyot7zABkzPvXfuaixZ5lryGxlKQ0CD3Q6WZYwy9rMuldfAqS5G4+2XDDR2rZr9e0SYRJrxYqUS/2P8QBq+rvCXYGaRrCsrtX5jDBkynmQRbe9ThUMhzKDe6wMvRmko45n7q+13flf4oJwAJw2M=
  - secure: ApvD5nYWTR4bKb8HHiVG/whCdNF4kWB2tzQtjkU0jkVizjT13QoHdRLENFBnDqP6nKSyuOqcga/9e6kEAOWwRlU90ew/FcbfDb3ikbY1e6gZLtyvcj9maOTT/Rdl0Yq5+c8+iw0SGSt4PRWXYk8r5WDOCvi7Bnk71V0d3CM86762fhsrTgHObZGuiKJ0Eq/UDDwaJvKKUjU8aHIfhGJqOvxSvfwzToMPFg79SNqBYih2pMFKXG7zh0jhkOPji3sUSwXvpLEV1vJ2d69z4ci4jbvKH5ZjxEG66QTbWXW5TFu90/f0Qb+dF83ATOMyMmJD6v4KyI0I+Slu052H5S+mW0VwjY2v51O9Or/RScYmVfJHqbNEFb659qkCbCBcfLKPhJvINZztPdbekYgLzLEfpjAyEZYMFZ3R4YI8zJwZkQR34ViSnikjgg83AlgVbbZ/W/VCH09kaa/04bOSeTRN0Aih973o2chTv8j1+mkyNpFFnN/4MAutYbOv5TKpfqJP/o8ZGsN293CQvNht2VYmv6FicP+9HdlDYHcpkHcYT0/cY45sFmm9KGGNaxTxJHCwV9h7qEar+Wd0S5/cgLWp72IfudmuTDHg17xSMwtWJZ+/xP0xPUpGvN4GhKB1aDohpfOqwQDtnFggNRDLDZPsn88X7ONXg8a0LYQC6AopDgY=
